export const DO_LOGIN = 'DO_LOGIN';
export const DO_LOGIN_RES = 'DO_LOGIN_RES';
export const DO_LOGIN_ERROR = 'DO_LOGIN_ERROR';

export const DO_SIGNUP = 'DO_SIGNUP';
export const DO_SIGNUP_RES = 'DO_SIGNUP_RES';

export const DO_VERIFICATION = 'DO_VERIFICATION';
export const DO_VERIFICATION_RES = 'DO_VERIFICATION_RES';

export const CHECK_USER = 'CHECK_USER';
export const CHECK_USER_RES = 'CHECK_USER_RES';

export const CREATE_RETRO = 'CREATE_RETRO';
export const CREATE_RETRO_RES = 'CREATE_RETRO_RES';

export const INVITE_RETRO = 'INVITE_RETRO';
export const INVITE_RETRO_RES = 'INVITE_RETRO_RES';

export const All_RETRO_PROJECTS = 'All_RETRO_PROJECTS';
export const All_RETRO_PROJECTS_RES = 'All_RETRO_PROJECTS_RES';

export const All_SPECIFIC_TEMPLATES = 'All_SPECIFIC_TEMPLATES';
export const All_SPECIFIC_TEMPLATES_RES = 'All_SPECIFIC_TEMPLATES_RES';

export const DO_TEMPLATE = 'DO_TEMPLATE';
export const DO_TEMPLATE_RES = 'DO_TEMPLATE_RES';

export const All_MY_TEMPLATES = 'All_MY_TEMPLATES';
export const All_MY_TEMPLATES_RES = 'All_MY_TEMPLATES_RES';

export const GET_TEMPLATE = 'GET_TEMPLATE';
export const GET_TEMPLATE_RES = 'GET_TEMPLATE_RES';

export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const CREATE_TEMPLATE_RES = 'CREATE_TEMPLATE_RES';

export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const UPDATE_TEMPLATE_RES = 'UPDATE_TEMPLATE_RES';

export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const DELETE_TEMPLATE_RES = 'DELETE_TEMPLATE_RES';

export const RETRO_LIST = 'RETRO_LIST';
export const RETRO_LIST_RES = 'RETRO_LIST_RES';

export const FIND_USERS_LIST = 'FIND_USERS_LIST';
export const FIND_USERS_LIST_RES = 'FIND_USERS_LIST_RES';

export const ALL_USERS_LIST = 'ALL_USERS_LIST';
export const ALL_USERS_LIST_RES = 'ALL_USERS_LIST_RES';

export const DO_UPDATE_USERS = 'DO_UPDATE_USERS';
export const DO_UPDATE_USERS_RES = 'DO_UPDATE_USERS_RES';

export const CHANGE_PWD = 'CHANGE_PWD';
export const CHANGE_PWD_RES = 'CHANGE_PWD_RES';

export const NEW_CREATE_TEMPLATE = 'NEW_CREATE_TEMPLATE';
export const NEW_CREATE_TEMPLATE_RES = 'NEW_CREATE_TEMPLATE_RES';

export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_SINGLE_USER_RES = 'GET_SINGLE_USER_RES';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_RES = 'DELETE_USER_RES';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_RES = 'CREATE_USER_RES';

export const GET_SINGLE_RETRO = 'GET_SINGLE_RETRO';
export const GET_SINGLE_RETRO_RES = 'GET_SINGLE_RETRO_RES';

export const DO_UPDATE_RETRO = 'DO_UPDATE_RETRO';
export const DO_UPDATE_RETRO_RES = 'DO_UPDATE_RETRO_RES';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_RES = 'DELETE_PROJECT_RES';

export const CREATE_THOUGHT = 'CREATE_THOUGHT';
export const CREATE_THOUGHT_RES = 'CREATE_THOUGHT_RES';

export const GET_ALL_THOUGHT = 'GET_ALL_THOUGHT';
export const GET_ALL_THOUGHT_RES = 'GET_ALL_THOUGHT_RES';

export const UPDATE_THOUGHT = 'UPDATE_THOUGHT';
export const UPDATE_THOUGHT_RES = 'UPDATE_THOUGHT_RES';

export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_RES = 'UPDATE_ACTIVITY_RES';

export const INVITE_USER_RETRO = 'INVITE_USER_RETRO';
export const INVITE_USER_RETRO_RES = 'INVITE_USER_RETRO_RES';

export const INVITE_USER_DELETE = 'INVITE_USER_DELETE';
export const INVITE_USER_DELETE_RES = 'INVITE_USER_DELETE_RES';

export const All_INVITE = 'All_INVITE';
export const All_INVITE_RES = 'All_INVITE_RES';

export const ADD_CARD = 'ADD_CARD';
export const ADD_CARD_RES = 'ADD_CARD_RES';

export const GET_INVOICE_HISTORY = 'GET_INVOICE_HISTORY';
export const GET_INVOICE_HISTORY_RES = 'GET_INVOICE_HISTORY_RES';

export const GET_CARD_DETAIL = 'GET_CARD_DETAIL';
export const GET_CARD_DETAIL_RES = 'GET_CARD_DETAIL_RES';

export const GET_USER_COUNT = 'GET_USER_COUNT';
export const GET_USER_COUNT_RES = 'GET_USER_COUNT_RES';

export const CREATE_BILLING = 'CREATE_BILLING';
export const CREATE_BILLING_RES = 'CREATE_BILLING_RES';

export const DO_START_RETRO = 'DO_START_RETRO';
export const DO_START_RETRO_RES = 'DO_START_RETRO_RES';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_RES = 'UPDATE_NOTE_RES';

export const DO_JOIN_RETRO = 'DO_JOIN_RETRO';
export const DO_JOIN_RETRO_RES = 'DO_JOIN_RETRO_RES';

export const COMPANY_LIST = 'COMPANY_LIST';
export const COMPANY_LIST_RES = 'COMPANY_LIST_RES';

export const DELETE_THOUGHT = 'DELETE_THOUGHT';
export const DELETE_THOUGHT_RES = 'DELETE_THOUGHT_RES';


export const GUEST_JOIN_RETRO = 'GUEST_JOIN_RETRO';
export const GUEST_JOIN_RETRO_RES = 'GUEST_JOIN_RETRO_RES';

export const INVOICE_LIST = 'INVOICE_LIST';
export const INVOICE_LIST_RES = 'INVOICE_LIST_RES';

export const RETRO_DELETE = 'RETRO_DELETE';
export const RETRO_DELETE_RES = 'RETRO_DELETE_RES';


export const ARCHIVE_TEMPLATE = 'ARCHIVE_TEMPLATE';
export const ARCHIVE_TEMPLATE_RES = 'ARCHIVE_TEMPLATE_RES';


export const GET_ACCOUNT_DETAIL = 'GET_ACCOUNT_DETAIL';
export const GET_ACCOUNT_DETAIL_RES = 'GET_ACCOUNT_DETAIL_RES';


// ************ super admin actions

export const DO_SUPER_LOGIN = 'DO_SUPER_LOGIN';
export const DO_SUPER_LOGIN_RES = 'DO_SUPER_LOGIN_RES';

export const GET_PLAN_LIST = 'GET_PLAN_LIST';
export const GET_PLAN_LIST_RES = 'GET_PLAN_LIST_RES';

export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_RES = 'CREATE_PLAN_RES';

export const GET_PLAN_DETAIL = 'GET_PLAN_DETAIL';
export const GET_PLAN_DETAIL_RES = 'GET_PLAN_DETAIL_RES';

export const UPDATE_PLAN = 'UPDATE_PLAN';
export const UPDATE_PLAN_RES = 'UPDATE_PLAN_RES';

export const DELETE_PLAN = 'DELETE_PLAN';
export const DELETE_PLAN_RES = 'DELETE_PLAN_RES';

export const GET_PROMOCODE_LIST = 'GET_PROMOCODE_LIST';
export const GET_PROMOCODE_LIST_RES = 'GET_PROMOCODE_LIST_RES';

export const CREATE_PROMOCODE = 'CREATE_PROMOCODE';
export const CREATE_PROMOCODE_RES = 'CREATE_PROMOCODE_RES';

export const GET_PROMOCODE_DETAIL = 'GET_PROMOCODE_DETAIL';
export const GET_PROMOCODE_DETAIL_RES = 'GET_PROMOCODE_DETAIL_RES';

export const UPDATE_PROMOCODE = 'UPDATE_PROMOCODE';
export const UPDATE_PROMOCODE_RES = 'UPDATE_PROMOCODE_RES';

export const DELETE_PROMOCODE = 'DELETE_PROMOCODE';
export const DELETE_PROMOCODE_RES = 'DELETE_PROMOCODE_RES';

export const GET_CUSTOM_TEMPLATE = 'GET_CUSTOM_TEMPLATE';
export const GET_CUSTOM_TEMPLATE_RES = 'GET_CUSTOM_TEMPLATE_RES';

export const GET_SINGLE_CUSTOM_TEMPLATE = 'GET_SINGLE_CUSTOM_TEMPLATE';
export const GET_SINGLE_CUSTOM_TEMPLATE_RES = 'GET_SINGLE_CUSTOM_TEMPLATE_RES';

export const CREATE_CUSTOM_TEMPLATE = 'CREATE_CUSTOM_TEMPLATE';
export const CREATE_CUSTOM_TEMPLATE_RES = 'CREATE_CUSTOM_TEMPLATE_RES';

export const UPDATE_CUSTOM_TEMPLATE = 'UPDATE_CUSTOM_TEMPLATE';
export const UPDATE_CUSTOM_TEMPLATE_RES = 'UPDATE_CUSTOM_TEMPLATE_RES';

export const DELETE_CUSTOM_TEMPLATE = 'DELETE_CUSTOM_TEMPLATE';
export const DELETE_CUSTOM_TEMPLATE_RES = 'DELETE_CUSTOM_TEMPLATE_RES';

export const GET_GLOBAL_TEMPLATE = 'GET_GLOBAL_TEMPLATE';
export const GET_GLOBAL_TEMPLATE_RES = 'GET_GLOBAL_TEMPLATE_RES';

export const GET_SINGLE_GLOBAL_TEMPLATE = 'GET_SINGLE_GLOBAL_TEMPLATE';
export const GET_SINGLE_GLOBAL_TEMPLATE_RES = 'GET_SINGLE_GLOBAL_TEMPLATE_RES';

export const CREATE_GLOBAL_TEMPLATE = 'CREATE_GLOBAL_TEMPLATE';
export const CREATE_GLOBAL_TEMPLATE_RES = 'CREATE_GLOBAL_TEMPLATE_RES';

export const UPDATE_GLOBAL_TEMPLATE = 'UPDATE_GLOBAL_TEMPLATE';
export const UPDATE_GLOBAL_TEMPLATE_RES = 'UPDATE_GLOBAL_TEMPLATE_RES';

export const DELETE_GLOBAL_TEMPLATE = 'DELETE_TEMPLATE';
export const DELETE_GLOBAL_TEMPLATE_RES = 'DELETE_GLOBAL_TEMPLATE_RES';





